require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SectionGridsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # SectionGrid. As you add validations to SectionGrid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SectionGridsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all section_grids as @section_grids" do
      section_grid = SectionGrid.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:section_grids)).to eq([section_grid])
    end
  end

  describe "GET show" do
    it "assigns the requested section_grid as @section_grid" do
      section_grid = SectionGrid.create! valid_attributes
      get :show, {:id => section_grid.to_param}, valid_session
      expect(assigns(:section_grid)).to eq(section_grid)
    end
  end

  describe "GET new" do
    it "assigns a new section_grid as @section_grid" do
      get :new, {}, valid_session
      expect(assigns(:section_grid)).to be_a_new(SectionGrid)
    end
  end

  describe "GET edit" do
    it "assigns the requested section_grid as @section_grid" do
      section_grid = SectionGrid.create! valid_attributes
      get :edit, {:id => section_grid.to_param}, valid_session
      expect(assigns(:section_grid)).to eq(section_grid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SectionGrid" do
        expect {
          post :create, {:section_grid => valid_attributes}, valid_session
        }.to change(SectionGrid, :count).by(1)
      end

      it "assigns a newly created section_grid as @section_grid" do
        post :create, {:section_grid => valid_attributes}, valid_session
        expect(assigns(:section_grid)).to be_a(SectionGrid)
        expect(assigns(:section_grid)).to be_persisted
      end

      it "redirects to the created section_grid" do
        post :create, {:section_grid => valid_attributes}, valid_session
        expect(response).to redirect_to(SectionGrid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved section_grid as @section_grid" do
        post :create, {:section_grid => invalid_attributes}, valid_session
        expect(assigns(:section_grid)).to be_a_new(SectionGrid)
      end

      it "re-renders the 'new' template" do
        post :create, {:section_grid => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested section_grid" do
        section_grid = SectionGrid.create! valid_attributes
        put :update, {:id => section_grid.to_param, :section_grid => new_attributes}, valid_session
        section_grid.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested section_grid as @section_grid" do
        section_grid = SectionGrid.create! valid_attributes
        put :update, {:id => section_grid.to_param, :section_grid => valid_attributes}, valid_session
        expect(assigns(:section_grid)).to eq(section_grid)
      end

      it "redirects to the section_grid" do
        section_grid = SectionGrid.create! valid_attributes
        put :update, {:id => section_grid.to_param, :section_grid => valid_attributes}, valid_session
        expect(response).to redirect_to(section_grid)
      end
    end

    describe "with invalid params" do
      it "assigns the section_grid as @section_grid" do
        section_grid = SectionGrid.create! valid_attributes
        put :update, {:id => section_grid.to_param, :section_grid => invalid_attributes}, valid_session
        expect(assigns(:section_grid)).to eq(section_grid)
      end

      it "re-renders the 'edit' template" do
        section_grid = SectionGrid.create! valid_attributes
        put :update, {:id => section_grid.to_param, :section_grid => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested section_grid" do
      section_grid = SectionGrid.create! valid_attributes
      expect {
        delete :destroy, {:id => section_grid.to_param}, valid_session
      }.to change(SectionGrid, :count).by(-1)
    end

    it "redirects to the section_grids list" do
      section_grid = SectionGrid.create! valid_attributes
      delete :destroy, {:id => section_grid.to_param}, valid_session
      expect(response).to redirect_to(section_grids_url)
    end
  end

end
